### PR TITLE
 Show warning if module is not installed on internal storage

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by rovo89** [comment]
Looks very good now, thanks! One thing I'm not sure about: Do we need to escape apostrophes in strings? 

And sorry for being very nitpicky sometimes, but the blank line before isInstalledOnExternalStorage() shouldn't have any blanks. I have enabled indicators for leading and trailing spaces in my editor to spot such things.

Anyway, this is something I can correct when merging this (I would combine it into a single commit with you as author anyway), this is just for the future. ;)


There's one more thing that came to my mind. The version check is also performed when writing the module list: https://github.com/rovo89/XposedInstaller/blob/master/src/de/robv/android/xposed/installer/util/ModuleUtil.java#L203
I guess we should do the same for the two new checks. This would make sense if an already enabled module is moved to external storage later. I assume it triggers a broadcast handled by Xposed Installer (would be good to test it!), so this would remove the module out of the modules.list file and thus avoid the "file not found" messages.

**Comment by pylerSM** [comment]
- Fixed apostrophes for newly added strings
- Removed spaces

Now I can look in ModuleUtil.

>And sorry for being very nitpicky sometimes
That's OK. Code readability is important for such a big project.

**Comment by pylerSM** [comment]
So condition like this?
> if (module.minVersion > installedXposedVersion || module.minVersion < MIN_MODULE_VERSION || module.isInstalledOnExternalStorage() || module.isForwardLocked())

**Comment by rovo89** [comment]
I'd go for the second condition.

**Comment by pylerSM** [comment]
Ok, I will rewrite it.


BTW (off topic) https://github.com/rovo89/XposedInstaller/blob/cdb3f47895f5543eca0ff94861f5a98b343213c6/src/de/robv/android/xposed/installer/InstallerFragment.java#L902 --> executing "reboot recovery" don't work on some devices?

**Comment by rovo89** [comment]
> executing "reboot recovery" don't work on some devices?

Yes. Xperia devices it was I think.

**Comment by pylerSM** [comment]
I disabled my xposed module using "pm disable pkg" and after reboot it was loaded normally and module perfomed all modifications.

I think we should handle even this state, when app is disabled. I will update this PR.

**Comment by rovo89** [comment]
This should already be handled.

**Comment by pylerSM** [comment]
>> This should already be handled. 

Then it is broken. I tested it some minutes ago and even if module is disabled (pm disable), it still works.

**Comment by pylerSM** [comment]
I see no "getApplicationEnabledSetting" in your code yet. So how you check if module is disabled by system disable feature?

**Comment by rovo89** [comment]
Check ModuleUtil around line 71. I use the enabled flag in application info. Such modules are not considered installed, so they should not be shown in the module fragment and should be removed from the file. Maybe you rebooted before the receiver could rewrite the file?

**Comment by pylerSM** [comment]
I disabled module via pm, waited for some minutes & then rebooted. After reboot I couldn't find module in menu and xposed modules list, but module features were working.

Afaik, it is strange. if you reenable module using pm, "module update notification" is shown (receiver got action) But if you disable it using pm, nothing is shown (no action or what? file with xposed modules list is not updated).

Now I know patches to show UI about this is useless (since modules are hidden). We need just this.
https://github.com/rovo89/XposedInstaller/pull/254

**Comment by rovo89** [comment]
This has been working, so please let's not blow up this feature request with "fixes" for possible bugs. I don't have the time to merge this at the moment, but once I have, I will only merge the parts for SD card/forward locked.

The handling for disabled modules is a different issue. It should work like this: When you execute "pm disable", it will trigger the PackageChangeReceiver with ACTION_PACKAGE_CHANGED. That will call reloadSingleModule(). As the module is not enabled then, it will return null and will also trigger an immediate reload of the module list UI. If the module had been enabled before, it will be deactivated and the module list will be updated, which should show a toast message. So my suggestion is that you follow this control flow and see where it stops unexpectedly (maybe simply add some more toasts for testing). If you find something, please create a new issue or pull request for it.

**Comment by darkyuhoo01** [comment]
Releases only
Be notified only for new releases, or when participating or @mentioned

**Pull request closed without merging**
