### PR TITLE
Show toast when downloads are disabled

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by rovo89** [comment]
I was actually thinking about displaying a message instead of the white fragment. ;) The toast disappears rather fast.

Or alternatively, maybe the "Download" items in the navigation should go away completely? From user experience point of view, it would avoid offering an option that basically does nothing. A possible downside might be that the user might not remember he has disabled downloads in the settings. Any opinions on this?

**Comment by pylerSM** [comment]
Maybe show red warning "Downloading modules is disabled." below "Download" in navigation view? Just like when there are new updates we can see green info message.

And disable access to this section too.

**Comment by pylerSM** [comment]
But maybe good way is also simply show AlertDialog
title - Downloads are disabled
msg - Downloading modules is disabled. Please enable it in Settings.

**Comment by pylerSM** [comment]
Ideas:
- Add Enable button to this dialog, which will directly enable downloads.
- Change OK button to "Open Settings" button.

Waiting for you comments.

**Pull request closed without merging**
